version: 2.0
jobs:
   deploy:
      machine:
         enabled: true
      steps:
         -  run:
               name: Deploy Over SSH
               command: |
                  ssh $SSH_USER@$SSH_HOST "rm -r streaming-api && git clone https://github.com/jdnhix/streaming-api.git && cd streaming-api && npm install"

workflows:
   version: 2
   build-and-deploy:
      jobs:
         - deploy:
              filters:
                 branches:
                    only: master


